# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aagasa/worker/v1/recording.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aagasa/worker/v1/recording.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n aagasa/worker/v1/recording.proto\x12\x10\x61\x61gasa.worker.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x02\n\x11RecordingMetadata\x12\x14\n\x0crecording_id\x18\x01 \x01(\t\x12\x0f\n\x07pass_id\x18\x02 \x01(\t\x12\x11\n\tworker_id\x18\x03 \x01(\t\x12\x12\n\nstation_id\x18\x04 \x01(\t\x12\x15\n\rrelative_path\x18\x05 \x01(\t\x12\x12\n\nsize_bytes\x18\x06 \x01(\x04\x12\x17\n\x0f\x63hecksum_sha256\x18\x07 \x01(\t\x12.\n\nstarted_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0b\x66inished_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"m\n\x16UploadRecordingRequest\x12\x37\n\x08metadata\x18\x01 \x01(\x0b\x32#.aagasa.worker.v1.RecordingMetadataH\x00\x12\x0f\n\x05\x63hunk\x18\x02 \x01(\x0cH\x00\x42\t\n\x07payload\"S\n\x17UploadRecordingResponse\x12\x14\n\x0crecording_id\x18\x01 \x01(\t\x12\x0e\n\x06stored\x18\x02 \x01(\x08\x12\x12\n\nsize_bytes\x18\x03 \x01(\x04\"r\n\x0f\x45xecutionRecord\x12\x0f\n\x07pass_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\x12/\n\x0brecorded_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"`\n\x17ReportExecutionsRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x32\n\x07records\x18\x02 \x03(\x0b\x32!.aagasa.worker.v1.ExecutionRecord\",\n\x18ReportExecutionsResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\rB(Z&aagasa/internal/gen/worker/v1;workerv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aagasa.worker.v1.recording_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&aagasa/internal/gen/worker/v1;workerv1'
  _globals['_RECORDINGMETADATA']._serialized_start=88
  _globals['_RECORDINGMETADATA']._serialized_end=350
  _globals['_UPLOADRECORDINGREQUEST']._serialized_start=352
  _globals['_UPLOADRECORDINGREQUEST']._serialized_end=461
  _globals['_UPLOADRECORDINGRESPONSE']._serialized_start=463
  _globals['_UPLOADRECORDINGRESPONSE']._serialized_end=546
  _globals['_EXECUTIONRECORD']._serialized_start=548
  _globals['_EXECUTIONRECORD']._serialized_end=662
  _globals['_REPORTEXECUTIONSREQUEST']._serialized_start=664
  _globals['_REPORTEXECUTIONSREQUEST']._serialized_end=760
  _globals['_REPORTEXECUTIONSRESPONSE']._serialized_start=762
  _globals['_REPORTEXECUTIONSRESPONSE']._serialized_end=806
# @@protoc_insertion_point(module_scope)
