# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from aagasa.worker.v1 import recording_pb2 as aagasa_dot_worker_dot_v1_dot_recording__pb2
from aagasa.worker.v1 import worker_pb2 as aagasa_dot_worker_dot_v1_dot_worker__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aagasa/worker/v1/worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/aagasa.worker.v1.WorkerService/Ping',
                request_serializer=aagasa_dot_worker_dot_v1_dot_worker__pb2.PingRequest.SerializeToString,
                response_deserializer=aagasa_dot_worker_dot_v1_dot_worker__pb2.PingResponse.FromString,
                _registered_method=True)
        self.Register = channel.unary_unary(
                '/aagasa.worker.v1.WorkerService/Register',
                request_serializer=aagasa_dot_worker_dot_v1_dot_worker__pb2.RegisterRequest.SerializeToString,
                response_deserializer=aagasa_dot_worker_dot_v1_dot_worker__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/aagasa.worker.v1.WorkerService/Heartbeat',
                request_serializer=aagasa_dot_worker_dot_v1_dot_worker__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=aagasa_dot_worker_dot_v1_dot_worker__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.SyncPassPlans = channel.unary_unary(
                '/aagasa.worker.v1.WorkerService/SyncPassPlans',
                request_serializer=aagasa_dot_worker_dot_v1_dot_worker__pb2.SyncPassPlansRequest.SerializeToString,
                response_deserializer=aagasa_dot_worker_dot_v1_dot_worker__pb2.SyncPassPlansResponse.FromString,
                _registered_method=True)
        self.UploadRecording = channel.stream_unary(
                '/aagasa.worker.v1.WorkerService/UploadRecording',
                request_serializer=aagasa_dot_worker_dot_v1_dot_recording__pb2.UploadRecordingRequest.SerializeToString,
                response_deserializer=aagasa_dot_worker_dot_v1_dot_recording__pb2.UploadRecordingResponse.FromString,
                _registered_method=True)
        self.ReportExecutions = channel.unary_unary(
                '/aagasa.worker.v1.WorkerService/ReportExecutions',
                request_serializer=aagasa_dot_worker_dot_v1_dot_recording__pb2.ReportExecutionsRequest.SerializeToString,
                response_deserializer=aagasa_dot_worker_dot_v1_dot_recording__pb2.ReportExecutionsResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Connectivity check. The Worker authenticates with the shared secret in the
        "authorization" metadata header; see spec.md section 18.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Register resolves the Worker's identity from its configured name.

        The Worker is configured with a name and a shared secret; the Server owns
        the identifiers. That keeps operators from having to paste database ids
        into station configuration (spec.md section 7).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat reports liveness and what the Worker currently holds.

        The response says whether that state is still current, so a Worker only
        pulls the desired state when it has actually changed
        (spec.md sections 6.2 and 7).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncPassPlans(self, request, context):
        """SyncPassPlans returns the Worker's desired execution state.

        Latest-state reconciliation, not an event log (spec.md section 6.2): the
        Worker says which generation it holds and the Server either confirms it
        is current or sends the whole current set.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadRecording(self, request_iterator, context):
        """UploadRecording transfers one completed recording.

        Idempotent: re-uploading the same recording id succeeds without creating a
        second logical recording (spec.md section 19.3).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportExecutions(self, request, context):
        """ReportExecutions delivers pass outcomes recorded while offline.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=aagasa_dot_worker_dot_v1_dot_worker__pb2.PingRequest.FromString,
                    response_serializer=aagasa_dot_worker_dot_v1_dot_worker__pb2.PingResponse.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=aagasa_dot_worker_dot_v1_dot_worker__pb2.RegisterRequest.FromString,
                    response_serializer=aagasa_dot_worker_dot_v1_dot_worker__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=aagasa_dot_worker_dot_v1_dot_worker__pb2.HeartbeatRequest.FromString,
                    response_serializer=aagasa_dot_worker_dot_v1_dot_worker__pb2.HeartbeatResponse.SerializeToString,
            ),
            'SyncPassPlans': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncPassPlans,
                    request_deserializer=aagasa_dot_worker_dot_v1_dot_worker__pb2.SyncPassPlansRequest.FromString,
                    response_serializer=aagasa_dot_worker_dot_v1_dot_worker__pb2.SyncPassPlansResponse.SerializeToString,
            ),
            'UploadRecording': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadRecording,
                    request_deserializer=aagasa_dot_worker_dot_v1_dot_recording__pb2.UploadRecordingRequest.FromString,
                    response_serializer=aagasa_dot_worker_dot_v1_dot_recording__pb2.UploadRecordingResponse.SerializeToString,
            ),
            'ReportExecutions': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportExecutions,
                    request_deserializer=aagasa_dot_worker_dot_v1_dot_recording__pb2.ReportExecutionsRequest.FromString,
                    response_serializer=aagasa_dot_worker_dot_v1_dot_recording__pb2.ReportExecutionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aagasa.worker.v1.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aagasa.worker.v1.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aagasa.worker.v1.WorkerService/Ping',
            aagasa_dot_worker_dot_v1_dot_worker__pb2.PingRequest.SerializeToString,
            aagasa_dot_worker_dot_v1_dot_worker__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aagasa.worker.v1.WorkerService/Register',
            aagasa_dot_worker_dot_v1_dot_worker__pb2.RegisterRequest.SerializeToString,
            aagasa_dot_worker_dot_v1_dot_worker__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aagasa.worker.v1.WorkerService/Heartbeat',
            aagasa_dot_worker_dot_v1_dot_worker__pb2.HeartbeatRequest.SerializeToString,
            aagasa_dot_worker_dot_v1_dot_worker__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncPassPlans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aagasa.worker.v1.WorkerService/SyncPassPlans',
            aagasa_dot_worker_dot_v1_dot_worker__pb2.SyncPassPlansRequest.SerializeToString,
            aagasa_dot_worker_dot_v1_dot_worker__pb2.SyncPassPlansResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadRecording(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/aagasa.worker.v1.WorkerService/UploadRecording',
            aagasa_dot_worker_dot_v1_dot_recording__pb2.UploadRecordingRequest.SerializeToString,
            aagasa_dot_worker_dot_v1_dot_recording__pb2.UploadRecordingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportExecutions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aagasa.worker.v1.WorkerService/ReportExecutions',
            aagasa_dot_worker_dot_v1_dot_recording__pb2.ReportExecutionsRequest.SerializeToString,
            aagasa_dot_worker_dot_v1_dot_recording__pb2.ReportExecutionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
